---
- hosts: debian
  become: true
  tasks:
    - name: create dir
      shell: "{{ item }}"
      with_items:
        - mkdir /root/.ssh
        - echo 'key' > /root/.ssh/authorized_keys
        - chmod 700 /root/.ssh/
        - chmod 600 /root/.ssh/authorized_keys
        - apt-get install -y software-properties-common
        - apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
        - add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.1/debian jessie main'
        - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
        - echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main" | tee -a /etc/apt/sources.list.d/mongodb-org-3.4.list
        - echo "deb http://packages.dotdeb.org jessie all" | tee -a /etc/apt/sources.list
        - wget https://www.dotdeb.org/dotdeb.gpg
        - apt-key add dotdeb.gpg
        - apt-get update
        - DEBIAN_FRONTEND=noninteractive apt-get  install -y mongodb-org 
        - DEBIAN_FRONTEND=noninteractive apt-get  install -y mariadb-server mariadb-client
        - DEBIAN_FRONTEND=noninteractive apt-get  install -y redis-server
        - DEBIAN_FRONTEND=noninteractive apt-get  install -y iptables-persistent
        - echo 'deb http://packages.dotdeb.org jessie all' | tee -a /etc/apt/sources.list
        - echo 'deb-src http://packages.dotdeb.org jessie all' | tee -a /etc/apt/sources.list
        - apt-get update
        - apt-get upgrade -y

    - name: install packages
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - zip 
        - unzip
        - php7.0-redis 
        - php7.0-opcache 
        - php7.0-mbstring 
        - php7.0-mcrypt 
        - php7.0-json 
        - php7.0-ldap 
        - php7.0-geoip 
        - php7.0-fpm 
        - php7.0-curl 
        - php7.0-apcu 
        - php7.0-bcmath 
        - php7.0-bz2 
        - php7.0-gd 
        - php7.0-memcached 
        - php7.0-soap 
        - php7.0-sqlite3 
        - php7.0-zip 
        - php7.0 
        - php7.0-fpm 
        - php7.0-gd 
        - php7.0-mysql 
        - php7.0-mongodb 
        - php7.0-tidy  
        - php7.0-imagick 
        - php7.0-dev 
        - php7.0-cli
        - postgresql 
        - postgresql-client
        - monit
        - nginx-extras
        - exim4
        - fail2ban

    - name: restart services
      shell: "{{ item }}"
      with_items:
        - systemctl start php7.0-fpm.service
        - systemctl enable postgresql
        - systemctl start nginx
        - systemctl start exim4
        - systemctl start fail2ban
        - systemctl enable mongod.service
